name: workflow3.yml
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make build
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - name: Installation des dépendances
        run: pip install ifaddr psutil pylint
      - name: Exécution du test
        run: pylint --disable=missing-docstring script/mysystem/mysystem.py