name: TP10-enchainer-les-workflows-CI
on:
  workflow_dispatch:

jobs:

  C-compilation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: sysinfo compilation
        run: make build
      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'bin/sysinfo'
      - name: sysinfo upload artifacts
        uses: actions/upload-artifact@v6
        with:
          path: bin/sysinfo
          name: sysinfo-${{ github.sha }}
          retention-days: 1
          compression-level: '9'