name: TP10-enchainer-les-workflows-CI
on:
  push:
    branches:
      - 'feature/**'
    tags:
      - 'v*.*.*'

jobs:

  C-lint:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: sysinfo lint
        run: make lint

  C-compilation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    needs: C-lint
    # S'exécute si le lint a réussi OU s'il a été skippé (cas des tags)
    if: |
      always() &&
      (
      (startsWith(github.ref, 'refs/tags/v') && needs.C-lint.result == 'skipped')
      ||
      (startsWith(github.ref, 'refs/heads/feature/') && needs.C-lint.result == 'success')
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: sysinfo compilation
        run: make build
      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'bin/sysinfo'
      - name: sysinfo upload artifacts
        uses: actions/upload-artifact@v6
        with:
          path: bin/sysinfo
          name: sysinfo-${{ github.sha }}
          retention-days: 1
          compression-level: '9'